#include QMK_KEYBOARD_H
#include "layers.h"
#include "vandalt.h"

#define LAYOUT_LR(...) LAYOUT(__VA_ARGS__)

combo_t key_combos[] = {
    VANDALT_COMBOS
};

const uint16_t PROGMEM keymaps[][MATRIX_ROWS][MATRIX_COLS] = {
  [BASE] = LAYOUT_WRAPPER(VANDALT_BASE_LAYER),
  [SYM] = LAYOUT_WRAPPER(VANDALT_SYM_LAYER),
  [NAV] = LAYOUT_WRAPPER(VANDALT_NAV_LAYER),
  [MEDIA] = LAYOUT_WRAPPER(VANDALT_MEDIA_LAYER),
  [MOUSE] = LAYOUT_WRAPPER(VANDALT_MOUSE_LAYER),
  [NOMOD] = LAYOUT_WRAPPER(VANDALT_NOMOD_LAYER)
};

