#include QMK_KEYBOARD_H
#include "layers.h"

#define LAYOUT_LR(...) LAYOUT(__VA_ARGS__)

const uint16_t PROGMEM keymaps[][MATRIX_ROWS][MATRIX_COLS] = {
  [BASE] = LAYOUT_WRAPPER(VANDALT_BASE_LAYER),
  [SYM] = LAYOUT_WRAPPER(VANDALT_SYM_LAYER),
  [NAV] = LAYOUT_WRAPPER(VANDALT_NAV_LAYER),
  [MOUSE] = LAYOUT_WRAPPER(VANDALT_MOUSE_LAYER),
  [NOMOD] = LAYOUT_WRAPPER(VANDALT_NOMOD_LAYER)
};
