#include QMK_KEYBOARD_H
#include "layers.h"

#define LAYOUT_LR(...) LAYOUT(__VA_ARGS__)

const uint16_t PROGMEM keymaps[][MATRIX_ROWS][MATRIX_COLS] = {
  [0] = LAYOUT_WRAPPER(VANDALT_BASE_LAYER),
  [1] = LAYOUT_WRAPPER(VANDALT_SYM_LAYER),
  [2] = LAYOUT_WRAPPER(VANDALT_NAV_LAYER),
  [3] = LAYOUT_WRAPPER(VANDALT_MOUSE_LAYER),
  [4] = LAYOUT_WRAPPER(VANDALT_NOMOD_LAYER)
};
