SRC += vandalt.c

CONSOLE_ENABLE = no
COMBO_ENABLE = yes
COMMAND_ENABLE = no
ORYX_ENABLE = yes
SPACE_CADET_ENABLE = no
CAPS_WORD_ENABLE = yes
DYNAMIC_TAPPING_TERM_ENABLE = yes
LAYER_LOCK_ENABLE = yes
AUDIO_ENABLE = no
REPEAT_KEY_ENABLE = yes
